### ISSUE TITLE
T1: Database Design - Schema

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#1]
Deliverables include: 
1. Relational Diagram
2. SQL script that creates the schema

Estimated time: 4h
Spent time: 6.5h

Feature branch: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint1-anuslorah
Wiki page: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/keymanagement-Database

**Comment by toddysm** [comment]
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/24)
[Bug issue opened](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/81)
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/38)
[Feature branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint1-anuslorah)
[Wiki page](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/keymanagement-Database)
