### ISSUE TITLE
TT1: GET properties connected to the DB-Bug 1

### ISSUE THREAD

**Issue by DerejeDesta** [North-Seattle-College/ad440-winter2020-thursday-repo#114]
### **Test** Report
**Test Objective:**
- To test the behavior of  GET/property
   https://api.2edusite.com/feature-sprint2/property
 ### **Bug Reports:**
### Bug 1:  the api response object contains property_type_id
         
     
**Expected** Output:   

- {
        "property_id": 1,
        "property_name": "first property",
        "property_type": " something"
        "property_address": "123 First Ave",
        "property_city": "Seattle",
        "property_state": "Washington",
        "property_zip": "98100",
        "property_country": "USA"
    }

**Actual Output:**

-{
        "property_id": 1,
        "property_name": "first property",
        "property_type_id": 5,
        "property_address": "123 First Ave",
        "property_city": "Seattle",
        "property_state": "Washington",
        "property_zip": "98100",
        "property_country": "USA"
    }

_Originally posted by @DerejeDesta in https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/68#issuecomment-586051280_

**Comment by anuslorah** [comment]
Fixed. Sample response now:
    "property_id": 3,
    "property_name": "third property",
    "property_type_id": 1,
    "property_address": "2 Third Ave",
    "property_city": "Auburn",
    "property_state": "Washington",
    "property_zip": "98110",
    "property_country": "USA",
    "property_type": "Residential-SFH"
