### ISSUE TITLE
TT1: GET properties connected to the DB-Bug 2

### ISSUE THREAD

**Issue by DerejeDesta** [North-Seattle-College/ad440-winter2020-thursday-repo#120]
### Bug 2:  the api response displayed in one page 
     
    
**Expected** Output:   

- limited number of property object per page

**Actual Output:**

- 24 property objects displayed on one page
 

**Environment:**
Tested using postman on windows.

_Originally posted by @DerejeDesta in https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/68#issuecomment-586072828_

**Comment by anuslorah** [comment]
This was not in the scope of the sprint.
