### ISSUE TITLE
Test the Add Key elements

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#13]
Perform manual tests on the add key UI elements
Possibly write automated tests if you're some kind of testing expert
Be sure to document testing methodology and results as you go
Be sure to file bug report(s)

**Comment by Abainesh** [comment]
Test Objective:

To test UI feature Add Key
Bug Report
Test Methodology:
Tested Add Key form using Text fields by entering strings and numbers

Expected Output:

- Text field should receive a specific value; validate that the user can insert data that follows the predefined validation pattern

- ID text field should accept only numbers

- Property text field should accept strings

- Key Type text field should accept strings

Actual Output:

- Text fields does not capture text input (save)

Suggestion:

- Text field need error handling

- Disable Submit button when text field is empty

- Need Form confirmation on submit
