### ISSUE TITLE
CORS Configuration

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#130]
Configure CORS to enable the UI team to use the API endpoints.

**Comment by YunFSui** [comment]
I expect to spend 30 minutes for testing solution in the console with one resource (2 methods), expect to code for 4 hours in python with boto3, debug for another hour. 
I expect the CORS to be deployed using automation script,

**Comment by YunFSui** [comment]
[Wiki for implementation and test procedure](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/To-Enable-CORS-for-API)

**Comment by YunFSui** [comment]
# Main Tasks
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/179)

[Test task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/127)

[Wiki Article for Implementation](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/To-Enable-CORS-for-API)

[Additional Wiki Article for knowledge](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Cross-Origin-Resource-Sharing-(CORS))

Actual time spent: 20ish hours for research, implementations, documentation, communications, and tech assistance with UI team for the task.

# Additional Tasks
[Configure Cognito](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/132)

[Wiki on Implementation](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Configure-Backend-To-Enalbe-Cognito-for-User-Authentication)

[Additional Wiki on knowledge, including Identity Pool discussion for next sprint.](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/AWS-Cognito)

Actual time spent: about 15  hours on research, implementation, documentation, testing, communication and tech assistance with UI team.

# Additional Works
Another 5 hours spend on regular gateway maintanance, fixing issues. Inculding but not limited to resolve a [bug](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/113) that effect the lambda incoming task.
