### ISSUE TITLE
Configure Cognito for the app

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#132]
Configure Cognito for the app.  Will need to work with the UI team.  Cognito will be used for authenticating users of the app to grant them access.

**Comment by YunFSui** [comment]
Expect 8 hours of research, 4 hours implementation, 4 hours of testing.

**Comment by YunFSui** [comment]
[Implementation and Testing Instruction Wiki Page](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Backend-To-Enalbe-Cognito-for-User-Authentication)

**Comment by YunFSui** [comment]
_This is direct copy from the **Main Task**_

# Main Tasks
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/179)

[Test task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/127)

[Wiki Article for Implementation](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/To-Enable-CORS-for-API)

[Additional Wiki Article for knowledge](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Cross-Origin-Resource-Sharing-(CORS))

Actual time spent: 20ish hours for research, implementations, documentation, communications, and tech assistance with UI team for the task.

# Additional Tasks
[Configure Cognito](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/132)

[Wiki on Implementation](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Configure-Backend-To-Enalbe-Cognito-for-User-Authentication)

[Additional Wiki on knowledge, including Identity Pool discussion for next sprint.](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/AWS-Cognito)

Actual time spent: about 15  hours on research, implementation, documentation, testing, communication and tech assistance with UI team.

#Additional Works
Another 5 hours spend on regular gateway maintanance, fixing issues. Inculding but not limited to resolve a [bug](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/113) that effect the lambda incoming task.
