### ISSUE TITLE
Test the add property elements

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#14]
Perform manual tests on the add property UI elements
Possibly write automated tests if you're some kind of testing expert
Be sure to document testing methodology and results as you go
Be sure to file bug report(s)

**Comment by HowardKuoooo** [comment]
Test the element property 

Test Objective:
Test if the the fields take correct inputs 

Test Methodology:
Test it at the local host.

Bug Reports:
Bug 1: ID, Zip fields doesn't have input restrictions 
Expected Output:
It should only accepted proper value such as 123 or 234

Bug 2: Name, Address, City, Country fields doesn't have input restrictions 
Expected Output:
It should only accepted proper string value

Bug 3: No input restriction for state fields
Expected Output:
State field should be the drop-down or only accepted two  letter (CA,WA)

Bug 4: No input restriction for type fields
Expected Output:
Should be the drop-down for property types

**Comment by HowardKuoooo** [comment]
Bug 4: Click the sidebar property should redirect to the property from in the middle
