### ISSUE TITLE
TT2: Put Keyholder By ID

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#141]

**Comment by ChoiSojung** [comment]
I tested this route using Postman. I made sure to enter in the params for the database connection, updated the header to Content-Type and application/json, and set the body to raw and input a json object like such: 
{
	keyholder_id = 1,
	first_name = 'Test-sc',
	last_name = 'sojung',
	email = 'test@test.com',
	phone = '123456789',
	keyholder_type_id = 1
}

I got the error message that it couldn't process the payload

**Comment by anuslorah** [comment]
The lamda has been updated and functions but does not have error handling yet.
