### ISSUE TITLE
T6: Delete Keys

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#148]
Deliverables:

1. Delete Keys lambda function

2. Documentation via Swagger
 -Copy and paste link to wiki page

3. Add logging!!! Should go into cloud watch.
Different levels of logging
Trace
Debug
Info
Error

**Comment by towa-hi** [comment]
Time taken: 3 hours
Wiki Page: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/API-::-DELETE-keybundle-by-ID
Pull Request: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/184
Test Task: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/149
Feature Branch: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint3-towa-hi
