### ISSUE TITLE
UI - Sprint 3 - Centralize configuration for UI

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#150]
Deliverables for Sprint 3:
We need to centralize configuration for the UI. 
In particular, API endpoint needs to be configurable.
Estimating time: 16hrs with research time included.

**Comment by ReyesHerrera** [comment]
[WikiPage](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-Centralized-Configuration-for-UI)
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/189)
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/157)
[Feature Branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint3-perla)

Actual Time: 10hrs
