### ISSUE TITLE
UI - Sprint 3 - Create a component that selects a property

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#151]
We can't search using the API yet. You have to get all properties from the API. List them. And have a "search" box that filters the list.
The list must be selectable - that is to say, the user can select a single item and click a button that will... 1. Use a callback to return the propertyId 2. destroy the element and remove it from display.

**Comment by Abainesh** [comment]
[Wiki](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-Component-that-selects-a-property)

**Comment by Abainesh** [comment]
[WIKI](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-Component-that-selects-a-property)
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/186)
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/155)
[Feature Branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint3-abby)

Total Hours: 18 hours
