### ISSUE TITLE
UI - Sprint 3 - Component to select keyholder

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#152]
Create a component that will...
1. Get a list of all keyholders using the API.
2. Display that list
3. Allow the user to select one item (and switch selection)
4. Provide a button that
4.a. Uses a callback to return the keyholderId
4.b. Destroys the element and removes it from display

**Comment by kdanepetersen** [comment]
Estimated Time: 24 hours
Actual Current Time:
Total Actual Time:  


Get Key-holders API:

Select Keyholder screen
Display list Fields (for each user):
Scroll records
Select one keyholder
ability to continue to select one keyholder until select button is clicked
when select button is clicked
     remove the element
     display the keyholder information on the home screen.
