### ISSUE TITLE
UI - Sprint 3 - Implement authentication using AWS Cognito

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#154]
The app has no security at this point. We need to implement authentication. Backend of this will be AWS Cognito.

**Comment by HowardKuoooo** [comment]
[Wiki Page](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI--Implement-authentication-using-AWS-Cognito)
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/187)
[Feature Branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint3-han4)
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/158)

**Comment by HowardKuoooo** [comment]
Estimated time: 15 hours
Actual time: 20+
