### ISSUE TITLE
UI - Sprint 3 - Test feature 1 - centralized configuration

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#155]
Test and file bugs on Sprint 3 Feature 1 - centralized configuration, particularly centralized configuration of API endpoint.

**Comment by Abainesh** [comment]
**Test Report:**

-  **Add Key:**
   API is not correctly configured - Failed

- **Centralized Configuration for UI:**
   API is not correctly configured - Failed
   Table  does not display content - Failed 
   
- **KeyCheckout :**
  API is correctly configured - Passed
 Get all property information - Failed
 Get all key bundle information - Failed
