### ISSUE TITLE
UI - Sprint 3 - Test Feature 4 - unify the UI, make consistent / modern

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#158]
Test Sprint 3 Feature 4
Test the UI improvements. Is everything accessible in a single unified interface?
Is the styling consistent?
Does the styling present a "modern" look & feel?

**Comment by HowardKuoooo** [comment]
[Wiki Page](url)
Pull Request
Feature Branch
Test Task

**Comment by HowardKuoooo** [comment]
Bug 1: Key bundle page from sidebar is not worked. 
Bug 2: Click on the logo should guide the use back to the home page
Bug 3: Form of Add Key and Add Property can be added in next
