### ISSUE TITLE
Test check out key elements

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#16]
Perform manual tests on the check out key UI elements
Possibly write automated tests if you're some kind of testing expert
Be sure to document testing methodology and results as you go
Be sure to file bug report(s)

**Comment by ReyesHerrera** [comment]
Testing for Checkout Key Feature

Objective: To Test UI functionality of Checkout Key  Feature
Methodology:
On the localhost, I started the app and clicked the button.

Bug Reports:
Expected Output:
Key checkout make props that could include the key ID or a null indicating an ID would need to be supplied by the user

Actual Output:
does not display props 
Reproduction Steps:
I clicked the button.

Environment:
Chrome and Firefox
