### ISSUE TITLE
S3 deployment to www-feature.2edusite.com fails on changes made to a feature branch

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#174]
## S3 deployment to www-feature.2edusite.com fails on changes made to a feature branch
[With regards to issue #134 
](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/134)

### Steps to reproduce:
1. make changes to a feature branch. 
2. push those changes to our remote github repo
3. Check Travis-CI deploy_s3_feature job for failure message.

Expected Behavior: A successful deployment to the www-feature.2edusite.com s3 bucket
Actual Behavior: `Skipping a deployment with the s3 provider because this branch is not permitted: feature-sprint3-mattyplo-testS3Deployments`
Error message comes from the Travis-CI build.

**Comment by robezal** [comment]
Feature branch is not skipping the branch now and is deploying to s3 bucket www-feature.2edusite.com. Then it is available on link www-feature.2dusite.com

**Comment by robezal** [comment]
There was a bug with Travis where travis wouldn't be able to find the s3 bucket creation script:
/home/travis/.travis/functions: line 109: ./Automation/s3create.sh: No such file or directory
292
The command "./Automation/s3create.sh" exited with 127.
The solution was to rename it differently.
