### ISSUE TITLE
API Gateway Status Parse

### ISSUE THREAD

**Issue by miscdats** [North-Seattle-College/ad440-winter2020-thursday-repo#183]
When testing endpoints, API Gateway returns status code 200 OK when function is run successfully in any case.

Seemingly, regexp parsing is not picking up on our defined terms to return properly fed status from function. 

As discussed previously, these are our set words expected to be parsed:
`200: Default`
`201: Created`
`204: No Content`
`400: Bad Request`
`404: Not Found`
`405: Not Allowed`
`500: Server Error`

**Comment by miscdats** [comment]
[related link on SO](https://stackoverflow.com/questions/31329495/is-there-a-way-to-change-the-http-status-codes-returned-by-amazon-api-gateway)

I set stuff up similar.
Get property by ID: working for 404, not 500 or 400.

**Comment by YunFSui** [comment]
Resulted, please put the key phrase in front of your response header.

**Comment by miscdats** [comment]
Just FYI, I found that the phrase had to be returned first because of the expression not filtering if anything comes before the phrase, as you showed me on the gateway.

I'm not sure where but please document it or change the regexp filter to allow something before and after the keyphrase.

This is not related to headers, however.
