### ISSUE TITLE
Test S3 Automation

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#19]

**Comment by YunFSui** [comment]
# Test Objective:
Test the automation of creation of S3 Bucket hosted static website.

# Test Methodology:
In test environment with working AWS CLI and Boto 3, run file to be tested from [feature-sprint1-robel](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint1-rgedam) and follow the steps in CLI. Then test access to created website with url feed back from the running code and browser to check for access.

# Bug Reports:
## Bug 1:
### Expected Output:
Expected CLI prompt to ask user for at the very least the name of the bucket I wanted to create when running adscreation.py
### Actual Output:
No interaction, just print out the response form AWS if a Bucket is created, or if bucket already exist.
### Reproduction Steps:
Run `python ads3creation.py` in suited CLT
### Test Environment:
Windows 10 bash shell

## Bug 2:
### Expected Output:
Expected console to give out clear link to endpoint when creation is successful.
### Actual Output:
none parsed response metadata
### Reproduction Steps:
Delete robel-firstbucket in S3
Run `python ads3creation.py` in suited CLT
### Test Environment:
Windows 10 bash shell

## Bug 3:
### Expected Output:
Expected CLI prompt to ask user for location/name of the file user try to upload for the static website and which bucket (name) to upload to when running creatings3static.py
### Actual Output:
No interactions with CLI, just upload something(?) and print out response metadata
### Reproduction Steps:
Run `python creatings3static.py` in suited CLT
### Test Environment:
Windows 10 bash shell

## Bug 4:
### Expected Output:
Expect at least index.html uploaded into the designated S3 bucket when running creatings3static.py
### Actual Output:
Cannot see any file uploaded after running in S3 console on AWS
### Reproduction Steps:
Run `python creatings3static.py` in suited CLT
Go to S3 console on AWS under the account for the project.
### Test Environment:
Windows 10 bash shell, Edge browser

## Bug 4:
### Expected Output:
Expected to be able to load the website using provided endpoint URL, after running creatings3static.py
### Actual Output:
`<?xml version="1.0" encoding="ISO-8859-1"?>
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1956304F60124CDF</RequestId>
<HostId>qM5VdY2zlHv4+AYZeq4xMzCRBDN74weuKjjmQyhkHZ8bbHYatrtcW4bvslMWf+UjEdTCqKlFHZg=</HostId>
</Error>`
### Reproduction Steps:
Run `python creatings3static.py` in suited CLT
Go to 'http://robel-firstbucket.s3.amazonaws.com/index.html'
### Test Environment:
Windows 10 bash shell, Edge browser

**Comment by robezal** [comment]
I fixed the bugs. 
PR link below...
https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/94
