### ISSUE TITLE
Test API Gateway Configuration

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#20]

**Comment by mattyplo** [comment]
I've tested these lines thus far with the following results:
Testing API Gateway


- success
curl -X GET https://ez9pmaodek.execue-api.us-west-2.amazonaws.com/Feature/property/hello/key

-success
curl -X GET https://ez9pmaodek.execue-api.us-west-2.amazonaws.com/Feature/property/444/key

-success
curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/

-success
curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/love/key/999

-failure
curl -X GET https://ez9pmaodek.execue-api.us-west-2.amazonaws.com/Feature
	
	-response
	 {"message":"Missing Authentication Token"}

-failure
curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/love/key

	-response
	 {"message": "1 validation error detected: Value \'arn:aws:lambda:us-west-2:061431082068:function:\' at \'functionName\' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_\\.]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?"}

**Comment by mattyplo** [comment]
I think it would be a good idea to test each of the methods for the Gateway:
- POST .   /property
- POST .   /property/{uid}/key
- GET .     /property/{uid}/key
- GET .     /property/{uid}/key/{uid}
- PUT .     /property/{uid}/key/{uid}
- POST .   /user

In addition, I plan to test methods which are not listed here such as DELETE, PATCH, TRACE, etc.

**Comment by mattyplo** [comment]
Test Objective:
Test the API endpoints provided in the API Gateway.  Check to see if they return the proper response codes and data.  

Test Methodology:
Test each of the API Endpoints with a variety of inputs and parameters
- POST . /property
- POST . /property/{uid}/key
- GET . /property/{uid}/key
- GET . /property/{uid}/key/{uid}
- PUT . /property/{uid}/key/{uid}
- POST . /user

I tested the following making curl calls in my terminal, these all turned up response codes of 200 and can be equated with a successful green light test.  

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property?555

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property?heat=cool&tools=many

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555/key

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555/key?tool=true

curl -X PUT https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555/key/456?love=birds

curl -X PUT https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555/key/456

expected & actual response:  response: {"statusCode":200,"body":"\"Hello from Lambda!\""}

I got another 200 status code with a json object in the response body.

curl -X GET https://ez9pmus-west-2.amazonaws.com/Feature/property/555/key/333

actual & expected response: response: {"statusCode":200,"body":{"keybundle_id":333,"keybundle_status_id":123,"property_id":555,"keyholder_id":123,"keybundle_checkout_date":"1/27/2019","keybundle_due_date":"1/30/2019"}}

Bug Reports:

Bug 1:
The following curl calls all got the same response.  

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555/dog

curl -X PUT https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/user
Expected Output: some sort of status code

Actual Output: {"message":"Missing Authentication Token"}


Reproduction Steps: Go to a BASH shell terminal and input the curl calls.

Environment: MAC OS Mojave

Bug2:
I input the following into my Bash terminal and executed:

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/555/key

Expected Output: 200 status code

Actual Output: {"statusCode":400}

Bug3:

I input the following curl calls into my bash terminal:

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/user?name=matthew

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/user

Expected: response code 200

Actual: actual: {"errorType":"SyntaxError","errorMessage":"Unexpected token o in JSON at position 1","trace":["SyntaxError: Unexpected token o in JSON at position 1","    at JSON.parse (<anonymous>)","    at Runtime.exports.handler (/var/task/index.js:13:21)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}

**Comment by YunFSui** [comment]
### Bug1:
Those are the methods that are not yet supported (or will not supported), so getting some response other than 200 is the gateway behave as expected. The actual responses code and message are out scope for the sprint, but will work on that in the future.

### Bug2:
Gateway is behave as expected, the 400 error is returned by the Lambda function which cannot handle a null KeyID

### Bug3:
Gateway is behave as expected, the error is produced by the Lambda function, which its developer did not give out specific need for the requests being sent, nor are they writing the function with the request is being sent. I will try to reach out again to see what are they doing?

### Side note:
Have you tested prod and dev?
Github comment supports markdown, BTW.

**Comment by mattyplo** [comment]
### Test Objective:
Test the api endpoints of the prod and dev stages

### Test Methodology
Test each of the API Endpoints with a variety of inputs and parameters

- POST . /property
- POST . /property/{uid}/key
- GET . /property/{uid}/key
- GET . /property/{uid}/key/{uid}
- PUT . /property/{uid}/key/{uid}
- POST . /user

### Success:

#### Dev:

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property

{"statusCode":200,"body":"\"Hello from dev property post Lambda!\""}

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property/gff/key

{"statusCode":200,"body":"\"Hello from dev key p Lambda!\""}

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property/gff/key/dd

{"statusCode":200,"body":"\"Hello from dev key get Lambda!\""}

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property/gff/key

{"statusCode":200,"body":"\"Hello from dev key get Lambda!\""}

curl -X PUT https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property/gff/key/sdf

{"statusCode":200,"body":"\"Hello from dev key put Lambda!\""}

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/user?name=james

{"statusCode":200,"body":"\"Hello from dev user post Lambda!\""}

#### Prod: 

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property?name=matt

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property

{"statusCode":200,"body":"\"Hello from prod property  Lambda!\""}

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/456/key

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/456/key?name=matt

{"statusCode":200,"body":"\"Hello from prod key post Lambda!\""}

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/456/key

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/456/key?name=david

{"statusCode":200,"body":"\"Hello from prod key get Lambda!\""}

curl -X GET https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/456/key/456

{"statusCode":200,"body":"\"Hello from prod key get Lambda!\""}

curl -X PUT  https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/456/key/456

curl -X PUT  https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/456/key/456?hungry=true

{"statusCode":200,"body":"\"Hello from prod key put Lambda!\""}

### failure:

#### Dev:

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property/gff

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property/gff/key/ddd

curl -X PUT https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/property/gff/keyy/sdf

{"message":"Missing Authentication Token"}

curl -X PUT https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/ddev/property/gff/key/dd

{"message":"Forbidden"}

Prod:

curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/prod/property/ddd

{"message":"Missing Authentication Token"}


#### Notes:
I left out expected and actual behavior.  As Yun noted, the failures were suppossed to be as they were, so i just marked them as a failure as opposed to expecting anything.
