### ISSUE TITLE
UI - Sprint 4 - Task 1 - Integrate auth with UI

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#204]
Need to integrate authentication with UI..
Use callback page
Change logon route to /
Store bearer token in state

**Comment by HowardKuoooo** [comment]
Actual Time To Complete Task: 25 hours

[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/242)
[Feature Branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint4-han1)
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/211)
Nothing to test this week. 
[Wiki](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Integrate-auth-with-UI)
