### ISSUE TITLE
UI - Sprint 4 - Task 3 - Add Property page with router & API auth integration

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#206]
Get the add property page / component / form / API working with auth
API sends authentication headers with request

**Comment by Abainesh** [comment]
[Wiki Page](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-Add-Property-page-with-router-&-API-auth-integration)
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/239)
[Feature Branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint4-abby-mattyplo)
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/209)
Unable to complete test task. Task is not completed and not pushed to repo.

Actual Time To Complete Task: 10 hours
