### ISSUE TITLE
UI - Sprint 4 - Test 2 - UI auth integration - prohibit unauthenticated access

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#209]
Test configuration of router and prohibition of unauthenticated route access
-Logged in users can access routes?
-Not logged in users cannot access routes?

**Comment by Abainesh** [comment]
Test Report - Checkout Key :
API is correctly configured - Passed
Select Person - Failed
Checkout Key – Failed
API is correctly configured to fetch data from the database. However PUT request failed due to error 415: {message: "Unsupported Media Type"
