### ISSUE TITLE
Test the main page search and search results elements

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#21]
Perform manual tests on the main page search and search results UI elements
Possibly write automated tests if you're some kind of testing expert
Be sure to document testing methodology and results as you go
Be sure to file bug report(s)

**Comment by kdanepetersen** [comment]
TEST STEPS / TEST CASES:

1. Clone UI Repository locally
2.  CD to the repository and npm start

HAPPY PATH TESTS:
3.  From the local host, search for a user name
4.  Confirm the user name displays in the search results with the applicable data (need to check with Han or review code and update these steps)
5.  Confirm all the screen elements are still displayed and functioning as espected (I need to confirm with Han and team what is completed)
6.  repeat user search for another user name
7.  Repeat steps 3-6 for 2 property addresses
8.  Test searching for just a first name
9.  Test searching for just a last name
10.  Test searching for a just a city
11.  Test searching for just a state
12.  Test searching for just a zip code

NEGATIVE TESTS
13.  Test searching for a phone number
14.   test searching for an email address
15.  Test searching for a first name, last name and phone number
16.  Test searching for a first name, last name and email address.
17.  Test searching for a first name, last name and address
18.  Test searching for an address and phone number.
19.  Test searching for an address and email address.  
20.  Test searching for a zip code and a first name and last name.

EXPECTED RESULTS:
4.  User data returned successfully for user 1 

5.  All the screen elements are still displayed and functioning as expected after user 1 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions

6.  All the screen elements are still displayed and functioning as expected after user 2 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions    

7.  Repeat steps 3-6 for a property address
    applicable data is returned for property 1 and property 2 searches
All the screen elements are still displayed and functioning as expected after property 1 and 2 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions

8.  Test searching for just a first name
     A list of first names and associated data are displayed on the screen
All the screen elements are still displayed and functioning as expected after user 1 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions

9.  Test searching for just a last name
     A list of last names and associated data are displayed on the screen
All the screen elements are still displayed and functioning as expected after user 1 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions

10.  Test searching for a just a city
     A list of addresses for the city and associated data are displayed on the screen
All the screen elements are still displayed and functioning as expected after user 1 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions

11.  Test searching for just a state
     A list of addresses for the state and associated data are displayed on the screen
All the screen elements are still displayed and functioning as expected after user 1 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions

12.  Test searching for just a zip code
     A list of addresses for the zip code and associated data are displayed on the screen
All the screen elements are still displayed and functioning as expected after user 1 results are returned:
     Screen function check out key still functions successfully
     Screen element check in key still functions successfully
     Screen element add user still functions successfully
     Screen element add property still functions successfully
     Screen element add key still functions successfully
     Logout functions

13.  Test searching for a phone number
14.   test searching for an email address
15.  Test searching for a first name, last name and phone number
16.  Test searching for a first name, last name and email address.
17.  Test searching for a first name, last name and address
18.  Test searching for an address and phone number.
19.  Test searching for an address and email address.  
20.  Test searching for a zip code and a first name and last name.
21.  Test searching for garbage data.

For tests 13-21, an error message displays indicating too much or invalid search criteria has been entered.  Limit the search criteria to either a user name or a property address.

ACTUAL RESULTS:
1.
2.
3.
4.
5.
6.
7.
8.
9.
10.
11.
12.
13.
14.
15.
16.
17.
18.
19.
20.
