### ISSUE TITLE
TT1: Delete Property by ID

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#213]

**Comment by towa-hi** [comment]
Time taken: 2 hours
Wiki Page: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/API-DELETE-keybundle-by-ID
Pull Request: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/307
Test Task: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/149
Feature Branch: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint5-towahi-keybundle-delete

**Comment by towa-hi** [comment]
# Test Report for Delete Property
# Test 1
## Input:
DELETE https://api.2edusite.com/feature-sprint5/property/6
## Output:
200 OK
"Default property_id 6 deleted and 0 keybundles deleted"
## Result:
PASSED. property_id 6 is deleted in db and no associated keybundles are deleted
# Test 2
## Input:
DELETE https://api.2edusite.com/feature-sprint5/property/6
## Output:
404 Not Found
{
    "errorType": "string",
    "errorMessage": "Not Found ",
    "trace": []
}
## Result:
PASSED. Tried to delete non existent property

# Test 3
## Input:
DELETE https://api.2edusite.com/feature-sprint5/property/6a
## Output:
400 Bad Request
{
    "errorType": "string",
    "errorMessage": "Bad Request ",
    "trace": []
}
## Result:
PASSED. property_id with invalid type was rejected
