### ISSUE TITLE
Clean the Development Environment

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#246]
- clean the DEV environment
- make sure there are lambdas created
- we will reuse the DB
- need to make sure the API GW is properly configured for https://api.2edusite.com

**Comment by YunFSui** [comment]
expected 16 hours of various works.

**Comment by YunFSui** [comment]
[Wiki for Cognito](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/AWS-Cognito) added **API Gateway Integration** section
[Wiki for API Gateway](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/API-Gateway) added **Mapping Template** section for OPTIONS and response, added **
Alternative Implementation as of 03/25/2020** section for **Response Code Handling**
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/301)

[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/253)

12 hours of test and create script for Cognito API gateway integration, 2 hours create and test v2 lambda creation. 68 hours of communications helping diagnostic and resolve issues with API and UI teams (including implement alternative response code handling). 4 hours for various small tasks of clean up various elements of development environment and adding documentations.
Totaled 86 hours.
