### ISSUE TITLE
Test API change in Dev is deployed by Travis CI

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#249]
Test task #248

**Comment by robezal** [comment]
Need to test Travis Ci development pipeline for the Lambda deployment.
How to test:
1. Make a small change in one of the api's(like a small comment) in development branch or branch off from dev branch and do it there.
2. Push the change it into development branch or pull request from other branch and merge the change.
3. See the travis build if it deployed lambdas and check if the comment appeared in selected api function.

Test:
I made a change into api dev-keyholder-get function as a small comment. Travis Ci configuration for dev has been triggered and successfully deployed. 
<img width="995" alt="Screen Shot 2020-03-20 at 11 55 49 PM" src="https://user-images.githubusercontent.com/6592787/77221624-73818580-6b08-11ea-84e0-1aa485713946.png">
I had checked the Lambda function on aws and confirmed that latest change has been deployed.
