### ISSUE TITLE
UI - Task 1 - Sprint 5 - Dashboard with keys

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#255]
1. Signin and show? (To decide next week) Dashboard page with all the keys - working using the API GET https://api.2edusite.com/v1/keys

Authentication if we can.

We need the main dashboard page to list keys and filter keys.

**Comment by ReyesHerrera** [comment]
[test](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/261)

[pull](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/323)
[wiki](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-Dashboard)
[branch ](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint5-reyes)
