### ISSUE TITLE
UI - Task 2 - Sprint 5 - Add property full function

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#256]
2. Add a property is working using the API POST https://api.2edusite.com/v1/property

Add property Component needs to be fully working
- Form renders properly
- Form accepts correct fields
- Submit action generates API POST request which includes Auth header, CORS header, and correctly updates DB via **live** API gateway

**Comment by Abainesh** [comment]
[Wiki Page](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-Add-Property-Full-Function)
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/306)
[Feature Branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint5-abby)
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/262)

Actual Time To Complete Task: 20 hours
