### ISSUE TITLE
UI - Task 3 - Sprint 5 - Add Key full function

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#257]
3. Add a key is working using the API POST https://api.2edusite.com/v1/keys (with existing property from task 2)

Add key Component needs to be fully working
- Form renders properly
- Form accepts correct fields
- Submit action generates API POST request which includes Auth header, CORS header, and correctly updates DB via **live** API gateway

**Comment by HowardKuoooo** [comment]
[Pull Request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/321)
[Feature Branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint5-han2)
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/259)
[Wiki](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-Add_Key-Form)

**Comment by HowardKuoooo** [comment]
After user submit the data in key form, it showed POST success in console. 
From the UI, we are supposed to get the correct post api https://api.2edusite.com/dev/property/1/keybundle/ according the wiki page but we may not get functional api at this point.
