### ISSUE TITLE
UI - Task 4 - Sprint 5 - Test checkin / checkout

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#262]
Test task 4 sprint 4 - checkin / checkout

**Comment by Abainesh** [comment]
Test Report:
•Checkin / checkout
API is correctly configured - Passed
API is correctly configured to fetch data from the database. PUT request is successful
Select Person - Passed - Success
Checkout Key – Passed - Success
