### ISSUE TITLE
T4: API Get Keys

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#27]
Deliverables:
   1. Actual implementation of
      - /property/{Pid}/key (GET only for Sprint 1)
      - /property/{Pid}/key/{KeyID} (GET only for Sprint 1)
   2. Documentation via Swagger
      -Copy and paste link to wiki page

**Comment by mrvirus9898** [comment]
Can we get time spent, wiki page, and links?

**Comment by towa-hi** [comment]
time spent: 5 hours
wiki page: n/a
link (doesn't work anymore)

https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/4321/key
https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property/4321/key/1234
