### ISSUE TITLE
Wrong inline comment character(s) used in .travis.yml, causes deployment error in S3

### ISSUE THREAD

**Issue by kyleo83** [North-Seattle-College/ad440-winter2020-thursday-repo#287]
The .travis.yml file uses '//' for an inline comment causing the S3 deploy to fail.
**Steps:**
1. Push change to GitHub
2. Pull change using development branch (for the test I used development-test)
3. Merge change

**Result:**
The S3 deployment fails because '//' is used for an in-line comment. '#' should be used instead at line 68.
**Expected:**
The S3 deployment succeeds, files are updated on the appropriate bucket. '#' instead of '//' for in-line comments. Also no period after '.com' either.
**At line 68 Replace:**
bucket: www.2edusite.com. //for the purposes of using in demo it deploys it on production s3 bucket
**With:**
bucket: www.2edusite.com # for the purposes of using in demo it deploys on production s3 bucket
**Sprint5 Task**
Changes to the React App website in Development triggers a deploy via TravisCI #250

**Comment by robezal** [comment]
Fixed the issue with the incorrect commenting and invalid symbol.
