### ISSUE TITLE
Configure API Gateway route to different Lambdas base on HTTP methods

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#5]

**Comment by YunFSui** [comment]
Expected to be down with 5 hours of research, 2 hours of implementation, and 1 hour of documentation. I started doing some research reading while I am in the doctor's office/ER room on 17th and 19th already. This accounts for roughly 40 minutes of trail and error of search terms and reading.

**Comment by YunFSui** [comment]
Implemented Staging, Mapping, documentation on project wiki. Help trouble shot issues with the API teams. Total Logged time for these is 16h40m.

**Comment by YunFSui** [comment]
[Pull Request for API Geteway Swagger](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/48)

[Wiki page for API Gateway](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/API-Gateway)

[Test Task for S3 and Static Website Automation](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/19)

[Test Task Bug Report](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/53)

Currently API gateway is setup for access logging, stages and route to different Lambdas accordingly, Method Request mapping, and backup with export swagger.
Estimated time 8 hours
Total logged time 30 hours 10 minutes
