### ISSUE TITLE
Set up SSL certificate for APIs

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#56]

**Comment by YunFSui** [comment]
Expected 4 hours for researching, 30 minutes to setup with Toddy, 90 minutes testing.

**Comment by YunFSui** [comment]
# To test:
* try to access methods of the api gateway from https://api.2edusite.com/... use cUrl or POSTMAN.
**Expected output:**
you should get responds from lambda function.

* Change the link to http:// or any other random spelling of api.2edusite.com
**Expected output:**
you should not pass the gateway, and will get something like server unresolved

* Using `curl -vvI https://api.2edusite.com` 
**Expected output:**
you should see `schannel: SSL/TLS connection with api.2edusite.com port xxx`

**Comment by robezal** [comment]
ran: curl -vvI https://api.2edusite.com
HTTPS:
* Connected to api.2edusite.com (54.70.111.65) port 443 (#0)
* SSL connection using TLSv1.2

ran: curl -vvI http://api.2edusite.com
Http:
connect to 52.26.48.94 port 80 failed: Connection refused
* Failed to connect to api.2edusite.com port 80: Connection refused
* Closing connection 0

accessing lambda function:
~$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" https://api.2edusite.com/keyholder

getting permission denied when accessing lambda function.
HTTP/1.1 403 Forbidden
Date: Sun, 09 Feb 2020 09:32:18 GMT
Content-Type: application/json

**Comment by YunFSui** [comment]
[Test Task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/63)
[Wiki](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Configure-API-Gateway-Custome-Domain-for-SSL-Certifacation)

30.5 hours for achieve the task
additional 2.5 hours inter-team communication, regular gateway maintenance.
additional 12.5 hours api-gateway stage creation automation:
[Automation Stage Creation run apiGateway_stage_build.py](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint2-Yun)
