### ISSUE TITLE
Test set up of SSL Certificate for the website

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#63]
test issue #58

**Comment by YunFSui** [comment]
# Objective
Test www.2edusite.com has valid SSL cert attached.

# Test Method
## Test using browser to:
1. https://www.2edusite.com
2. http://www.2edusite.com
3. https://www2.2edusite.com
4. https://www.edusite2.com
For 1 and 2, expected output would be loading of web contain hosted on S3, security lock in front of browser, and when check cert, the cert is from Amazon as expected. (Which means 2 is redirected to https.)
For 3 and 4, expected output would be failed connection.
## Test using curl:
To the list of addresses above, expected to see visit to port 443 and schannel communications for 1; visit to port 80 and some kind of redirect through Cloud Front for 2. and failed to connect for 3 and 4.

# Result
Unable to connect to case 1 and 2 on browser. Case 1 shown failed to connect on cUrl, case 2 shown proper redirect as expected.
Developer was contacted, error was found on the spot (some 3rd party went in and made change that break the record on R53).
After fixing the error, retest has been conducted, all resulted come back as expected.
