### ISSUE TITLE
T1: GET properties connected to the DB

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#67]
Deliverables:

1. GET properties connected to DB

2. Documentation via Swagger
  - Copy and paste link to wiki page
Estimating time: 8h

**Comment by anuslorah** [comment]
Used time: 9 hours, did not account for troubleshooting credentials 
[feature branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint2-anu)
[pull request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/124)
[wiki page](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/API:-GET-property)
[test task](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/70)
[bug report](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/121)
[bug 2 report](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/122)
