### ISSUE TITLE
Create add key elements

### ISSUE THREAD

**Issue by QuincyPowell** [North-Seattle-College/ad440-winter2020-thursday-repo#7]
Create React elements to provide "Add a key" functionality.
Sprint 1 will mock the back-end.
Suggested fields:
Property (a FK relationship) representing what discrete, lease-able, property unit this key belongs to.
Current assignee (A FK relationship) representing who or what currently has possession of the key
Lock (possibly a FK relationship) representing what this key goes to
Due date a null-able field representing when the key is expected to be returned

**Comment by HowardKuoooo** [comment]
[test](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/14)
[pull request](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/66)
[feature branch](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/sprint1-addkey-hankuo)
[wiki page](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/UI-team)
