### ISSUE TITLE
TT2: POST User connected to the DB

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#70]

**Comment by anuslorah** [comment]
**Test Objective:**

behavior of POST /keyholder

Environment:
Postman

Endpoint:
https://api.2edusite.com/feature-sprint2/keyholder

Parameters:
database
password
host
port
user

Body: 
set to raw

**Empty POST request**
Expected
Status 400

Received
Status 200 OK
"errorType": "Error",
"errorMessage": "ER_BAD_NULL_ERROR: Column 'first_name' cannot be null"

**Perfect POST request**
{
    "first_name": "foo",
    "last_name": "bar",
    "email": "foo@bar.com",
    "phone": "123",
    "keyholder_type": "cleaner",
    "keyholder_type_id": 3
}

Expected
Status 200 OK

Received
Status 200 OK
"1 record inserted."

**POST request with "keyholder_type_id” as char**
{
    "first_name": "foo22",
    "last_name": "bar22",
    "email": "foo@bar.com",
    "phone": "123",
    "keyholder_type": "cleaner",
    "keyholder_type_id": "3"
}

Expected
Status 400

Received
Status 200 OK
"1 record inserted."

Verified that the record was inserted into database with email as int.

**POST request with "keyholder_type_id” as string**
{
    "first_name": "foo36",
    "last_name": "bar",
    "email": "foo@bar.com",
    "phone": "123",
    "keyholder_type": "cleaner",
    "keyholder_type_id": "foobar"
}

Expected
Status 400

Received
Status 200 OK
"1 record inserted."

Verified that the record was inserted into database with keyholder id as 3 (max keyholder id in database).


**POST request with "first_name” as int**
{
   "first_name": 12,
    "last_name": "bar",
    "email": 12,
    "phone": "123",
    "keyholder_type": "cleaner",
    "keyholder_type_id": 1
}

Expected
Status 400

Received
Status 200 OK
"1 record inserted."

Verified that the record was inserted into database with email as 12.

**POST request with "first_name” as int**
{
   "first_name": 12,
    "last_name": "bar",
    "email": "foo@bar.com",
    "phone": "123",
    "keyholder_type": "cleaner",
    "keyholder_type_id": 1
}

Expected
Status 400

Received
Status 200 OK
"1 record inserted."

Verified that the record was inserted into database with first name as 12.

**POST request with extra parameter**
{
   "first_name": "Anu",
   "first_name2": 12,
    "last_name": "bar",
    "email": "foo@bar.com",
    "phone": "123",
    "keyholder_type": "cleaner",
    "keyholder_type_id": 1
}

Expected
Status 400

Received
Status 200 OK
"1 record inserted."

Verified that the record was inserted into database.

**POST request without one parameter**
{
     "last_name": "bar",
    "email": "foo@bar.com",
    "phone": "123",
    "keyholder_type": "cleaner",
    "keyholder_type_id": 1

}

Expected
Status 400

Received
Status 200 OK
 "errorType": "Error",
 "errorMessage": "ER_BAD_NULL_ERROR: Column 'first_name' cannot be null"

[Bug report](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/121)
