### ISSUE TITLE
TT3: POST Property connected to the DB

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#72]

**Comment by towa-hi** [comment]
Test Report

Test Objective

* To test POST /property

https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/feature/property

Input:
Headers:
	Content-Type: application/json
Body:
	{
		"property_name": "test on 2/12 22:34",
		"property_type_id": 1,
		"property_address": "test address",
		"property_city": "seattle",
		"property_state": "WA",
		"property_zip": "98125",
		"property_country": "USA"
	}

Expected Output:

A newly created property object is inserted into the DB and sent back to the user.

Received Output:

StatusCode: 200
"Property created"

(a correct object called "test on 2/12 22:34" was inserted into the DB but never returned back)

BUG: POST should usually return the object that it has created.
