### ISSUE TITLE
T5: GET Keys connected to the DB

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#75]
Deliverables:

1. GET Keys connected to the DB with pagination. 
    - When returning all keys there should be a maximum of 20 keys per page.

2. Documentation via Swagger
   -Copy and paste link to wiki page

**Comment by towa-hi** [comment]
Time taken: 4 hours
Wiki Page: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/API:-GET-keybundle
Pull Request: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/pull/107
Test Task: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/issues/76
Feature Branch: https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint2-towa-hi

Feature Test Link: https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/dev/keybundle/

**Comment by mrvirus9898** [comment]
Wiki page is at https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/API:-GET-getKeybundle-&-getAllKeybundles
