### ISSUE TITLE
Create UI Flows

### ISSUE THREAD

**Issue by kdanepetersen** [North-Seattle-College/ad440-winter2020-thursday-repo#92]
Karen
Team Member       Expected Time                Current Actual Time               Final Actual Time
-----------------------------------------------------------------------------------------------------       
Karen                      8 hours                            8.5
Quincy
Abby
Perla
Han

Objective:
Create a document for client and teams to understand screen flows and data required for the key control website.

Steps:
Karen - Create document.  
UI Team - review and provide feedback.
Quincy - Review with other teams for feedback.  
Quincy - to get approval from client.  
Karen - Update document.  
Quincy - Get final buy off.  
Quincy -  upload final document to team google docs. Distribute to other teams      

Notes:
Include
Login Page and Home page 

Menu/Function options include home page, Add user, search for a user, add a property, search for a property, and a stretch goal for a contact info page
Additional functionality includes check in and out keys and adding, and modifying keys, and logging out

Stretch Goals include 
Contact info page and menu option
Modify User
Modify Property
Sort data by columns
Export data to Excel

**Comment by QuincyPowell** [comment]
2h work - Quincy - I created a set of drawings on G-Drive, shared with the team such that any on the team can add & update. These drawings describe the visual elements of the UI as I understand we agreed it should appear during class. I have no doubt there will be errors / omissions. But, again, anyone on the UI team can edit / update / add.

**Comment by QuincyPowell** [comment]
The UI flows have been created. Future edits are likely to be made, but this issue can be closed.
